header:
  # The `version` entry in the header describes for which configuration
  # format version this file was created for. It is used by kas to figure
  # out if it is compatible with this file. The version is an integer that
  # is increased on every format change.
  version: 11
  # The machine as it is written into the `local.conf` of bitbake.
machine: "mx6ul-kie-inverter"
# The distro name as it is written into the `local.conf` of bitbake.
distro: "kostal"
target: kie-image-base-swu
repos:
  # This entry includes the repository where the config file is located
  # to the bblayers.conf:
  meta-inverter-bsp-os:
    url: "https://github.com/kostal-solar/meta-inverter-bsp-os.git"
    refspec: 1d927250bbd7a5731318b473150f5d5d8f078e94
  # Here we include a list of layers from the poky repository to the
  # bblayers.conf:
  poky-os:
    url: "https://github.com/yoctoproject/poky.git"
    refspec: 65dafea22018052fe7b2e17e6e4d7eb754224d38
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp: exclude
  meta-security-os:
    url: "git://git.yoctoproject.org/meta-security"
    refspec: b5642c519b90f83ab6ec1507db9b3b36db43c548
  meta-openembedded-os:
    url: "git://git.openembedded.org/meta-openembedded"
    refspec: 82c75b466e55d7dca7a2364986ecb704cf63d141
    layers:
      meta-oe:
      meta-filesystems:
      meta-perl:
      meta-python:
      meta-networking:
  meta-swupdate-os:
    url: "https://github.com/sbabic/meta-swupdate.git"
    refspec: kirkstone
  
bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  kostal-opensource-project: |
    PATCHRESOLVE = "noop"
    #BB_NO_NETWORK = "1"
    BB_GENERATE_MIRROR_TARBALLS = "1"
    CONF_VERSION = "2"
    DL_DIR ?= "${TOPDIR}/work/yocto_downloads"
    SSTATE_DIR ?= "${TOPDIR}/work/sstate-cache"
    PACKAGE_CLASSES ?= "package_ipk"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    USER_CLASSES ?= "buildstats"
    PACKAGECONFIG:append_pn-qemu-native = " sdl"
    PACKAGECONFIG:append_pn-nativesdk-qemu = " sdl"
    INHERIT += "image-buildinfo"
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        ABORT,${TMPDIR},100M,1K \
        ABORT,${DL_DIR},100M,1K \
        ABORT,${SSTATE_DIR},100M,1K \
        ABORT,/tmp,10M,1K"
